package_name : regression_model

# Data files 
training_data_file : train.csv
test_data_file : test.csv

# Variables
target : SalePrice
pipeline_name : regression_model
pipeline_save_file : regression_model_output_v

# variables will cause syntax errors since they begin with a number
variables_to_rename:
  1stFlrSF : FirstFlrSF
features:
  - MSSubClass
  - MSZoning
  - LotArea
  - LotShape
  - LandContour
  - LotConfig
  - Neighborhood
  - Condition1
  - HouseStyle
  - OverallQual
  - YearRemodAdd
  - RoofStyle
  - Exterior1st
  - ExterQual
  - Foundation
  - BsmtQual
  - BsmtCond
  - BsmtExposure
  - BsmtFinType1
  - BsmtFinSF1
  - BsmtUnfSF
  - HeatingQC
  - CentralAir
  - FirstFlrSF
  - GrLivArea
  - BsmtFullBath
  - HalfBath
  - KitchenQual
  - TotRmsAbvGrd
  - Functional
  - Fireplaces
  - GarageYrBlt
  - GarageFinish
  - GarageCars
  - GarageArea
  - PavedDrive
  - WoodDeckSF
  - OpenPorchSF
  - ScreenPorch
  - SaleCondition
  - YrSold


test_size : 0.1 
random_state : 42
alpha: 0.001
categorical_vars_with_na_frequent:
  - BsmtQual
  - BsmtCond
  - BsmtExposure
  - BsmtFinType1
  - GarageFinish

numerical_vars_with_na:
  - GarageYrBlt

temporal_vars:
  - YearRemodAdd
  - GarageYrBlt

ref_var: YrSold

# variables to log transform
numericals_log_vars:
  - FirstFlrSF
  - GrLivArea

binarize_vars:
  - ScreenPorch

# variables to map
qual_vars:
  - ExterQual
  - BsmtQual
  - BsmtCond
  - HeatingQC
  - KitchenQual

exposure_vars:
  - BsmtExposure

finish_vars:
  - BsmtFinType1

garage_vars:
  - GarageFinish

categorical_vars:
  - MSSubClass
  - MSZoning
  - LotShape
  - LandContour
  - LotConfig
  - Neighborhood
  - Condition1
  - HouseStyle
  - RoofStyle
  - Exterior1st
  - Foundation
  - CentralAir
  - Functional
  - PavedDrive
  - SaleCondition

# variable mappings
qual_mappings:
  Po: 1
  Fa: 2
  TA: 3
  Gd: 4
  Ex: 5
  Missing: 0
  NA: 0

exposure_mappings:
  No: 1
  Mn: 2
  Av: 3
  Gd: 4


finish_mappings:
  Missing: 0
  NA: 0
  Unf: 1
  LwQ: 2
  Rec: 3
  BLQ: 4
  ALQ: 5
  GLQ: 6


garage_mappings:
  Missing: 0
  NA: 0
  Unf: 1
  RFn: 2
  Fin: 3